### ISSUE TITLE
[BUG] reload=True on service.running fails on debian stretch 

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/varnish-formula#18]
```
       ----------
                 ID: varnish
           Function: service.running
             Result: False
            Comment: Failed to reload varnish.service: Job type reload is not applicable for unit varnish.service.
              See system logs and 'systemctl status varnish.service' for details.
            Started: 10:42:21.744655
           Duration: 25.325 ms
            Changes:   
```
